/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CricketMatch {
  'id' : string,
  'matchType' : MatchType,
  'status' : MatchStatus,
  'result' : string,
  'venue' : string,
  'homeTeam' : Team,
  'date' : bigint,
  'tournament' : string,
  'homeScore' : Score,
  'awayTeam' : Team,
  'awayScore' : Score,
}
export type MatchStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'completed' : null };
export type MatchType = { 'odi' : null } |
  { 't20' : null } |
  { 'test' : null };
export interface NewsArticle {
  'title' : string,
  'date' : bigint,
  'summary' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface PlayerStats {
  'runs' : bigint,
  'team' : Team,
  'matches' : bigint,
  'wickets' : bigint,
  'playerName' : string,
}
export interface PointsTableEntry {
  'won' : bigint,
  'played' : bigint,
  'lost' : bigint,
  'team' : Team,
  'netRunRate' : number,
  'points' : bigint,
}
export interface Score { 'overs' : number, 'runs' : bigint, 'wickets' : bigint }
export interface Team {
  'flagEmoji' : string,
  'name' : string,
  'countryCode' : string,
}
export interface _SERVICE {
  'getAllMatches' : ActorMethod<[], Array<CricketMatch>>,
  'getAllNews' : ActorMethod<[], Array<NewsArticle>>,
  'getAllPlayerStats' : ActorMethod<[], Array<PlayerStats>>,
  'getAllPointsTable' : ActorMethod<[], Array<PointsTableEntry>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];