/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MatchType = IDL.Variant({
  'odi' : IDL.Null,
  't20' : IDL.Null,
  'test' : IDL.Null,
});
export const MatchStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const Team = IDL.Record({
  'flagEmoji' : IDL.Text,
  'name' : IDL.Text,
  'countryCode' : IDL.Text,
});
export const Score = IDL.Record({
  'overs' : IDL.Float64,
  'runs' : IDL.Int,
  'wickets' : IDL.Int,
});
export const CricketMatch = IDL.Record({
  'id' : IDL.Text,
  'matchType' : MatchType,
  'status' : MatchStatus,
  'result' : IDL.Text,
  'venue' : IDL.Text,
  'homeTeam' : Team,
  'date' : IDL.Int,
  'tournament' : IDL.Text,
  'homeScore' : Score,
  'awayTeam' : Team,
  'awayScore' : Score,
});
export const NewsArticle = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Int,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const PlayerStats = IDL.Record({
  'runs' : IDL.Int,
  'team' : Team,
  'matches' : IDL.Int,
  'wickets' : IDL.Int,
  'playerName' : IDL.Text,
});
export const PointsTableEntry = IDL.Record({
  'won' : IDL.Int,
  'played' : IDL.Int,
  'lost' : IDL.Int,
  'team' : Team,
  'netRunRate' : IDL.Float64,
  'points' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllMatches' : IDL.Func([], [IDL.Vec(CricketMatch)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAllPlayerStats' : IDL.Func([], [IDL.Vec(PlayerStats)], ['query']),
  'getAllPointsTable' : IDL.Func([], [IDL.Vec(PointsTableEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MatchType = IDL.Variant({
    'odi' : IDL.Null,
    't20' : IDL.Null,
    'test' : IDL.Null,
  });
  const MatchStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Team = IDL.Record({
    'flagEmoji' : IDL.Text,
    'name' : IDL.Text,
    'countryCode' : IDL.Text,
  });
  const Score = IDL.Record({
    'overs' : IDL.Float64,
    'runs' : IDL.Int,
    'wickets' : IDL.Int,
  });
  const CricketMatch = IDL.Record({
    'id' : IDL.Text,
    'matchType' : MatchType,
    'status' : MatchStatus,
    'result' : IDL.Text,
    'venue' : IDL.Text,
    'homeTeam' : Team,
    'date' : IDL.Int,
    'tournament' : IDL.Text,
    'homeScore' : Score,
    'awayTeam' : Team,
    'awayScore' : Score,
  });
  const NewsArticle = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Int,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const PlayerStats = IDL.Record({
    'runs' : IDL.Int,
    'team' : Team,
    'matches' : IDL.Int,
    'wickets' : IDL.Int,
    'playerName' : IDL.Text,
  });
  const PointsTableEntry = IDL.Record({
    'won' : IDL.Int,
    'played' : IDL.Int,
    'lost' : IDL.Int,
    'team' : Team,
    'netRunRate' : IDL.Float64,
    'points' : IDL.Int,
  });
  
  return IDL.Service({
    'getAllMatches' : IDL.Func([], [IDL.Vec(CricketMatch)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAllPlayerStats' : IDL.Func([], [IDL.Vec(PlayerStats)], ['query']),
    'getAllPointsTable' : IDL.Func([], [IDL.Vec(PointsTableEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };