/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PointsTableEntry {
    won: bigint;
    played: bigint;
    lost: bigint;
    team: Team;
    netRunRate: number;
    points: bigint;
}
export interface Score {
    overs: number;
    runs: bigint;
    wickets: bigint;
}
export interface CricketMatch {
    id: string;
    matchType: MatchType;
    status: MatchStatus;
    result: string;
    venue: string;
    homeTeam: Team;
    date: bigint;
    tournament: string;
    homeScore: Score;
    awayTeam: Team;
    awayScore: Score;
}
export interface NewsArticle {
    title: string;
    date: bigint;
    summary: string;
    imageUrl: string;
    category: string;
}
export interface PlayerStats {
    runs: bigint;
    team: Team;
    matches: bigint;
    wickets: bigint;
    playerName: string;
}
export interface Team {
    flagEmoji: string;
    name: string;
    countryCode: string;
}
export enum MatchStatus {
    upcoming = "upcoming",
    live = "live",
    completed = "completed"
}
export enum MatchType {
    odi = "odi",
    t20 = "t20",
    test = "test"
}
export interface backendInterface {
    getAllMatches(): Promise<Array<CricketMatch>>;
    getAllNews(): Promise<Array<NewsArticle>>;
    getAllPlayerStats(): Promise<Array<PlayerStats>>;
    getAllPointsTable(): Promise<Array<PointsTableEntry>>;
}
import type { CricketMatch as _CricketMatch, MatchStatus as _MatchStatus, MatchType as _MatchType, Score as _Score, Team as _Team } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllMatches(): Promise<Array<CricketMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNews(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNews();
            return result;
        }
    }
    async getAllPlayerStats(): Promise<Array<PlayerStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayerStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayerStats();
            return result;
        }
    }
    async getAllPointsTable(): Promise<Array<PointsTableEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPointsTable();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPointsTable();
            return result;
        }
    }
}
function from_candid_CricketMatch_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CricketMatch): CricketMatch {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_MatchType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchType): MatchType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    matchType: _MatchType;
    status: _MatchStatus;
    result: string;
    venue: string;
    homeTeam: _Team;
    date: bigint;
    tournament: string;
    homeScore: _Score;
    awayTeam: _Team;
    awayScore: _Score;
}): {
    id: string;
    matchType: MatchType;
    status: MatchStatus;
    result: string;
    venue: string;
    homeTeam: Team;
    date: bigint;
    tournament: string;
    homeScore: Score;
    awayTeam: Team;
    awayScore: Score;
} {
    return {
        id: value.id,
        matchType: from_candid_MatchType_n4(_uploadFile, _downloadFile, value.matchType),
        status: from_candid_MatchStatus_n6(_uploadFile, _downloadFile, value.status),
        result: value.result,
        venue: value.venue,
        homeTeam: value.homeTeam,
        date: value.date,
        tournament: value.tournament,
        homeScore: value.homeScore,
        awayTeam: value.awayTeam,
        awayScore: value.awayScore
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    odi: null;
} | {
    t20: null;
} | {
    test: null;
}): MatchType {
    return "odi" in value ? MatchType.odi : "t20" in value ? MatchType.t20 : "test" in value ? MatchType.test : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
}): MatchStatus {
    return "upcoming" in value ? MatchStatus.upcoming : "live" in value ? MatchStatus.live : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CricketMatch>): Array<CricketMatch> {
    return value.map((x)=>from_candid_CricketMatch_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
